# .github/release.yml

changelog:
  exclude:
    labels:
      - Ignore in Release 
    authors:
      - octocat
  categories:
    - title: New Features 🎉
      labels:
        - Feature
    - title: Other Changes
      labels:
        - "*"
