name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node 
        uses: actions/setup-node@v2
        with:
          node-version: 14.x 
          cache: 'yarn'
      - name: Install dependencies 
        run: yarn 
      - name: Lint
        run: yarn lint 
      - name: Stop MySQL
        run: sudo service mysql stop
      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          character set server: 'utf8' 
          collation server: 'utf8_general_ci'
          mysql version: '8.0' 
          mysql database: 'remark'
          mysql user: 'remark'
          mysql password: 'remark'
      - name: Generate Certs 
        run: yarn certs 
      - name: Test 
        run: yarn test
        env:
          NODE_ENV: development
          PORT: 5050
          DATABASE_URL: mysql://remark:remark@localhost:3306/remark
          HOST: http://localhost:3000
